spring.application.name=auth-service
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:mysql://localhost:3306/i_am_biker_db?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=SepptillioN21_SQL
server.port=8900

jwt.secret=9d5c3687c5dfa48ae9a7799eabf77d3c0de017797d75ed7d82e852ac358a6500
jwt.expiration=360000