version : '3.9'
services:
  naming-server:
    image: naming-server
    ports:
      - "8761:8080"

  api-gateway:
    image: api-gateway
    ports:
      - "8765:8080"
    depends_on:
      - authentication-service
      - maintenance-service
      - web-service
      - bikes-service
    env_file:
      - .env

  authentication-service:
    image: authentication-service
    env_file:
      - .env

  maintenance-service:
    image: maintenance-service

  web-service:
    image: web-service
    env_file:
      - .env

  bikes-service:
    image: bikes-service
    env_file:
      - .env
