server:
  port: 8765

jwt:
  secret: ${JWT_SECRET}
  expiration: 360000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      cache:
        enabled: false
    gateway:
      server:
        webflux:
          routes:
          - id: web-service
            uri: lb://WEB-SERVICE
            predicates:
              - Path=/web/**

          - id: authentication-service
            uri: lb://AUTHENTICATION-SERVICE
            predicates:
              - Path=/authentication/**

          - id: maintenance-service
            uri: lb://MAINTENANCE-SERVICE
            predicates:
              - Path=/maintenance/**

          - id: bikes-service
            uri: lb://BIKES-SERVICE
            predicates:
              - Path=/bikes/**
          - id: forum-service
            uri: lb://FORUM-SERVICE
            predicates:
                - Path=/forum/**
