spring.output.ansi.enabled=ALWAYS

logging.pattern.console=%red(%d{yyyy-MM-dd HH:mm:ss}) %highlight(%-5level){FBLUE} %cyan(%logger{36}) - %msg\n

logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.root=INFO