server:
  port: 8200
  servlet:
    context-path: /bikes

spring:
  application:
    name: bikes-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/i_am_biker_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Warsaw
    username: biker
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-refresh-interval: 10s

